import { worldLandPath, getCountryPath, COUNTRY_IDS, GEO_VIEWBOX } from './geoUtils';

// Extract simplified (world-atlas 110m = already simplified) paths
const countries = {
  India: COUNTRY_IDS.India,
  China: COUNTRY_IDS.China,
  USA: COUNTRY_IDS.USA,
  Russia: COUNTRY_IDS.Russia,
  Brazil: COUNTRY_IDS.Brazil,
  Australia: COUNTRY_IDS.Australia,
  UK: COUNTRY_IDS.UK,
  Japan: COUNTRY_IDS.Japan,
  SaudiArabia: COUNTRY_IDS.SaudiArabia,
  Iran: COUNTRY_IDS.Iran,
  SriLanka: COUNTRY_IDS.SriLanka,
  Pakistan: COUNTRY_IDS.Pakistan,
  Bangladesh: COUNTRY_IDS.Bangladesh,
  France: COUNTRY_IDS.France,
  Germany: COUNTRY_IDS.Germany,
  Turkey: COUNTRY_IDS.Turkey,
  Egypt: COUNTRY_IDS.Egypt,
  Nigeria: COUNTRY_IDS.Nigeria,
  SouthAfrica: COUNTRY_IDS.SouthAfrica,
  Indonesia: COUNTRY_IDS.Indonesia,
  Mexico: COUNTRY_IDS.Mexico,
  Canada: COUNTRY_IDS.Canada,
  UAE: COUNTRY_IDS.UAE,
};

const lines: string[] = [];
lines.push('/**');
lines.push(' * geo-paths.ts — Pre-computed SVG path strings from world-atlas 110m + d3-geo.');
lines.push(' * Source: Natural Earth 1:110m data via world-atlas npm package.');
lines.push(' * Projection: Natural Earth (geoNaturalEarth1), fitted to 1510×820 canvas.');
lines.push(' * India uses official Government of India (LGD) boundary — J&K, Arunachal correct.');
lines.push(' * Generated by: npx tsx geo/_extract-paths.ts');
lines.push(' * DO NOT hand-edit path strings — re-run the generator if you need changes.');
lines.push(' */');
lines.push('');
lines.push('/** ViewBox matching the geo template canvas (1510×820 Natural Earth projection) */');
lines.push(`export const GEO_VIEWBOX = "${GEO_VIEWBOX}";`);
lines.push('');
lines.push('/** Full world land outline — use as background for all world maps */');
lines.push(`export const WORLD_LAND = "${worldLandPath}";`);
lines.push('');
lines.push('/**');
lines.push(' * Country outline paths in Natural Earth projection (1510×820 canvas).');
lines.push(' * All paths match the GEO_VIEWBOX coordinate space.');
lines.push(' */');
lines.push('export const COUNTRY_PATHS = {');
for (const [name, id] of Object.entries(countries)) {
  const path = getCountryPath(id);
  lines.push(`  /** ${name} — ISO ${id} */`);
  lines.push(`  ${name}: "${path}",`);
  lines.push('');
}
lines.push('} as const;');
lines.push('');
lines.push('export type CountryPathKey = keyof typeof COUNTRY_PATHS;');

console.log(lines.join('\n'));
