#!/usr/bin/env python3
# ---
# varnam_script: project.intake
# owner: editor
# status: live
# surface: python3 scripts/run.py project:intake
# purpose: Project intake runner.
# use_when: Create canonical project inputs interactively or from JSON.
# inputs: CLI args, manifests, env vars, or imports documented by argparse/docstring
# outputs: files, JSON/stdout reports, or process exit code documented by the script
# authority: scripts/README.md; scripts/SCRIPT_MAP.md
# ---
"""Project intake runner for canonical `projects/<slug>/` bootstrap.

Two modes:
  - Interactive (default): prompts on the TTY, one field at a time.
  - Non-interactive: `--from-json <path>` reads a pre-filled dict and skips prompts.

The non-interactive mode is what the `intake` subagent uses once it has collected
the brief from the user in conversation. It also lets fixtures replay intake in
tests.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import tempfile
from dataclasses import dataclass, fields
from pathlib import Path


SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = Path(__file__).resolve().parents[2]
CHANNELS_DIR = REPO_ROOT / "channels"
SCAFFOLD_SCRIPT = SCRIPT_DIR / "scaffold.sh"


def normalize_slug(value: str) -> str:
    slug = value.strip().lower()
    out: list[str] = []
    prev_dash = False
    for ch in slug:
        if ch.isalnum():
            out.append(ch)
            prev_dash = False
            continue
        if not prev_dash:
            out.append("-")
            prev_dash = True
    normalized = "".join(out).strip("-")
    while "--" in normalized:
        normalized = normalized.replace("--", "-")
    return normalized


def dquote(value: str) -> str:
    return (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("$", "\\$")
        .replace("`", "\\`")
    )


def csv_to_bullets(raw: str, *, fallback: str) -> str:
    items = [item.strip() for item in raw.split(",") if item.strip()]
    if not items:
        return fallback
    return "\n".join(f"- {item}" for item in items)


def shell_var(name: str, value: str) -> str:
    return f'{name}="{dquote(value)}"'


@dataclass
class IntakeData:
    slug: str
    channel: str
    title_direction: str
    core_message: str
    why_now: str
    anti_goals: str
    target_viewer: str
    platform: str
    runtime: str
    desired_outcome: str
    format_name: str
    format_why: str
    hook_contract: str
    movement_contract: str
    ending_contract: str
    narration_stance: str
    visual_proof_modes: str
    sound_stance: str
    no_go_moves: str
    key_subjects: str
    exact_facts: str
    media_evidence_obligations: str
    research_requirements: str
    context_summary: str
    current_task: str
    next_task: str


def available_channels() -> list[str]:
    if not CHANNELS_DIR.exists():
        return []
    return sorted(path.name for path in CHANNELS_DIR.iterdir() if path.is_dir())


def prompt(label: str, *, default: str = "", required: bool = False) -> str:
    suffix = f" [{default}]" if default else ""
    while True:
        value = input(f"{label}{suffix}: ").strip()
        if value:
            return value
        if default:
            return default
        if not required:
            return ""
        print("Required.")


def confirm(prompt_text: str, *, default_no: bool = True) -> bool:
    suffix = " [y/N]: " if default_no else " [Y/n]: "
    value = input(f"{prompt_text}{suffix}").strip().lower()
    if not value:
        return not default_no
    return value in {"y", "yes"}


def build_intake_text(data: IntakeData) -> str:
    lines = [
        "# Generated by scripts/run.py project:intake",
        shell_var("SLUG", data.slug),
        shell_var("CHANNEL", data.channel),
        shell_var("TITLE_DIRECTION", data.title_direction),
        "",
        shell_var("CORE_MESSAGE", data.core_message),
        shell_var("WHY_NOW", data.why_now),
        "",
        shell_var("ANTI_GOALS", data.anti_goals),
        "",
        shell_var("TARGET_VIEWER", data.target_viewer),
        shell_var("PLATFORM", data.platform),
        shell_var("RUNTIME", data.runtime),
        shell_var("DESIRED_OUTCOME", data.desired_outcome),
        "",
        shell_var("FORMAT", data.format_name),
        shell_var("FORMAT_WHY", data.format_why),
        shell_var("HOOK_CONTRACT", data.hook_contract),
        shell_var("MOVEMENT_CONTRACT", data.movement_contract),
        shell_var("ENDING_CONTRACT", data.ending_contract),
        "",
        shell_var("NARRATION_STANCE", data.narration_stance),
        shell_var("VISUAL_PROOF_MODES", data.visual_proof_modes),
        shell_var("SOUND_STANCE", data.sound_stance),
        shell_var("NO_GO_MOVES", data.no_go_moves),
        "",
        shell_var("KEY_SUBJECTS", data.key_subjects),
        shell_var("EXACT_FACTS", data.exact_facts),
        shell_var("MEDIA_EVIDENCE_OBLIGATIONS", data.media_evidence_obligations),
        shell_var("RESEARCH_REQUIREMENTS", data.research_requirements),
        "",
        shell_var("CONTEXT_SUMMARY", data.context_summary),
        shell_var("CURRENT_TASK", data.current_task),
        shell_var("NEXT_TASK", data.next_task),
        "",
    ]
    return "\n".join(lines)


def build_summary(data: IntakeData) -> str:
    return "\n".join(
        [
            "",
            "Locked brief",
            f"- channel: {data.channel}",
            f"- slug: {data.slug}",
            f"- title: {data.title_direction or 'TBD'}",
            f"- core message: {data.core_message}",
            f"- why now: {data.why_now}",
            f"- platform/runtime: {data.platform} / {data.runtime}",
            f"- viewer: {data.target_viewer}",
            f"- format: {data.format_name}",
            f"- desired outcome: {data.desired_outcome}",
            f"- narration stance: {data.narration_stance}",
            f"- sound stance: {data.sound_stance}",
            "  key subjects:",
            *[f"  {line}" for line in data.key_subjects.splitlines()],
            "  research requirements:",
            *[f"  {line}" for line in data.research_requirements.splitlines()],
        ]
    )


def collect_intake(args: argparse.Namespace) -> IntakeData:
    channels = available_channels()
    default_channel = args.channel or (channels[0] if channels else "")
    if channels:
        print(f"Available channels: {', '.join(channels)}")
    channel = prompt("Channel", default=default_channel, required=True)
    if channels and channel not in channels:
        print(f"Warning: {channel!r} is not an existing channel directory.")

    channel_dir = CHANNELS_DIR / channel
    if channel_dir.exists():
        print(
            "Using channel defaults from "
            f"{channel_dir / 'design.md'}."
        )

    print("\nStep 1: shape")
    working_title = prompt("Working title", default=args.title or "", required=True)
    derived_slug = normalize_slug(args.slug or working_title)
    slug = normalize_slug(prompt("Slug", default=derived_slug, required=True))
    core_message = prompt("Core message", required=True)
    why_now = prompt("Why now", required=True)
    platform = prompt("Platform", default="YouTube", required=True)
    runtime = prompt("Runtime", default="300-360s", required=True)
    target_viewer = prompt("Target viewer", default="channel audience", required=True)
    desired_outcome = prompt(
        "Desired outcome",
        default="viewer retains the thesis",
        required=True,
    )

    print("\nStep 2: source-visible locks")
    anti_goals = csv_to_bullets(
        prompt("Anti-goals from user/channel (comma-separated, blank if none)"),
        fallback="- none locked yet",
    )
    key_subjects = csv_to_bullets(
        prompt("Key subjects visible in source/request (comma-separated, blank if none)"),
        fallback="- none locked yet",
    )
    exact_facts = csv_to_bullets(
        prompt("Exact facts / names / dates (comma-separated, blank if none)"),
        fallback="- none locked yet",
    )
    media_evidence = csv_to_bullets(
        prompt("Media / evidence obligations (comma-separated, blank if none)"),
        fallback="- none locked yet",
    )
    research_requirements = csv_to_bullets(
        prompt("Research requirements (comma-separated, blank = core/researcher verify source and stance)"),
        fallback="- core/researcher verify source claims and exact names/dates before package lock\n- core chooses active argument/stance before package lock",
    )

    print("\nStep 3: delivery defaults")
    format_name = prompt("Format", default="default", required=True)
    narration_stance = prompt("Narration stance override", default="channel default")
    visual_proof_modes = csv_to_bullets(
        prompt("Visual proof modes override (comma-separated, blank = channel default)"),
        fallback="- channel default",
    )
    sound_stance = prompt("Sound stance override", default="channel default")
    no_go_moves = csv_to_bullets(
        prompt("No-go moves override (comma-separated, blank = channel default)"),
        fallback="- channel default",
    )

    format_why = "- not yet locked"
    hook_contract = "- not yet locked"
    movement_contract = "- not yet locked"
    ending_contract = "- not yet locked"
    if confirm("Lock format behavior now?"):
        format_why = prompt("Why this format", required=True)
        hook_contract = prompt("Hook contract", required=True)
        movement_contract = prompt("Movement contract", required=True)
        ending_contract = prompt("Ending contract", required=True)

    title_direction = working_title
    context_summary = f"{core_message} Why now: {why_now}"
    current_task = "Review locked brief and start think-tank pass 1."
    next_task = "Write story/script.md from the locked brief."

    return IntakeData(
        slug=slug,
        channel=channel,
        title_direction=title_direction,
        core_message=core_message,
        why_now=why_now,
        anti_goals=anti_goals,
        target_viewer=target_viewer,
        platform=platform,
        runtime=runtime,
        desired_outcome=desired_outcome,
        format_name=format_name,
        format_why=format_why,
        hook_contract=hook_contract,
        movement_contract=movement_contract,
        ending_contract=ending_contract,
        narration_stance=narration_stance,
        visual_proof_modes=visual_proof_modes,
        sound_stance=sound_stance,
        no_go_moves=no_go_moves,
        key_subjects=key_subjects,
        exact_facts=exact_facts,
        media_evidence_obligations=media_evidence,
        research_requirements=research_requirements,
        context_summary=context_summary,
        current_task=current_task,
        next_task=next_task,
    )


def run_scaffold(data: IntakeData) -> int:
    intake_text = build_intake_text(data)
    temp_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            prefix="varnam-intake-",
            suffix=".sh",
            delete=False,
            encoding="utf-8",
        ) as handle:
            handle.write(intake_text)
            temp_path = Path(handle.name)

        proc = subprocess.run(
            [
                "bash",
                str(SCAFFOLD_SCRIPT),
                "--from",
                str(temp_path),
                "--source-label",
                "python3 scripts/run.py project:intake",
            ],
            cwd=REPO_ROOT,
            check=False,
        )
        return proc.returncode
    finally:
        if temp_path and temp_path.exists():
            temp_path.unlink()


FIELD_DEFAULTS = {
    "platform": "YouTube",
    "runtime": "300-360s",
    "target_viewer": "channel audience",
    "desired_outcome": "viewer retains the thesis",
    "format_name": "default",
    "narration_stance": "channel default",
    "sound_stance": "channel default",
    "visual_proof_modes": "- channel default",
    "no_go_moves": "- channel default",
    "research_requirements": "- core/researcher verify source claims and exact names/dates before package lock\n- core chooses active argument/stance before package lock",
    "format_why": "- not yet locked",
    "hook_contract": "- not yet locked",
    "movement_contract": "- not yet locked",
    "ending_contract": "- not yet locked",
}

EXPECTED_JSON_KEYS = {f.name for f in fields(IntakeData)} | {
    "working_title",  # alias for title_direction, convenient for humans
}


def _coerce_list_to_bullets(raw, *, fallback: str) -> str:
    if isinstance(raw, list):
        items = [str(item).strip() for item in raw if str(item).strip()]
        if not items:
            return fallback
        return "\n".join(f"- {item}" for item in items)
    if isinstance(raw, str):
        stripped = raw.strip()
        if not stripped:
            return fallback
        if stripped.startswith("- "):
            return stripped
        return csv_to_bullets(stripped, fallback=fallback)
    raise ValueError(f"expected list or string, got {type(raw).__name__}")


def load_intake_json(path: Path) -> IntakeData:
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        raise SystemExit(f"intake json not found: {path}")
    except json.JSONDecodeError as exc:
        raise SystemExit(f"intake json not valid: {exc}")
    if not isinstance(raw, dict):
        raise SystemExit("intake json must be a top-level object")

    unexpected = set(raw.keys()) - EXPECTED_JSON_KEYS
    if unexpected:
        raise SystemExit(f"intake json has unexpected keys: {sorted(unexpected)}")

    # working_title is a convenience alias for title_direction
    if "working_title" in raw and "title_direction" not in raw:
        raw["title_direction"] = raw.pop("working_title")
    elif "working_title" in raw:
        raw.pop("working_title")

    slug_seed = raw.get("slug") or raw.get("title_direction", "")
    slug = normalize_slug(raw.get("slug", slug_seed))
    if not slug:
        raise SystemExit("intake json missing slug and working_title")

    def req(key: str) -> str:
        value = raw.get(key)
        if value is None or (isinstance(value, str) and not value.strip()):
            raise SystemExit(f"intake json missing required field: {key}")
        return str(value).strip()

    def opt(key: str, default: str = "") -> str:
        value = raw.get(key)
        if value is None:
            return FIELD_DEFAULTS.get(key, default)
        text = str(value).strip()
        return text or FIELD_DEFAULTS.get(key, default)

    def list_field(key: str) -> str:
        if key not in raw:
            return FIELD_DEFAULTS.get(key, "- none locked yet")
        return _coerce_list_to_bullets(
            raw[key], fallback=FIELD_DEFAULTS.get(key, "- none locked yet")
        )

    title_direction = req("title_direction")
    core_message = req("core_message")
    why_now = req("why_now")

    data = IntakeData(
        slug=slug,
        channel=req("channel"),
        title_direction=title_direction,
        core_message=core_message,
        why_now=why_now,
        anti_goals=list_field("anti_goals"),
        target_viewer=opt("target_viewer"),
        platform=opt("platform"),
        runtime=opt("runtime"),
        desired_outcome=opt("desired_outcome"),
        format_name=opt("format_name"),
        format_why=opt("format_why"),
        hook_contract=opt("hook_contract"),
        movement_contract=opt("movement_contract"),
        ending_contract=opt("ending_contract"),
        narration_stance=opt("narration_stance"),
        visual_proof_modes=list_field("visual_proof_modes"),
        sound_stance=opt("sound_stance"),
        no_go_moves=list_field("no_go_moves"),
        key_subjects=list_field("key_subjects"),
        exact_facts=list_field("exact_facts"),
        media_evidence_obligations=list_field("media_evidence_obligations"),
        research_requirements=list_field("research_requirements"),
        context_summary=opt(
            "context_summary", default=f"{core_message} Why now: {why_now}"
        ),
        current_task=opt(
            "current_task",
            default="Review locked brief and start think-tank pass 1.",
        ),
        next_task=opt(
            "next_task", default="Write story/script.md from the locked brief."
        ),
    )
    return data


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Run a compact, channel-aware intake, confirm the locked brief, "
            "then scaffold the canonical projects/<slug>/ workspace."
        )
    )
    parser.add_argument("--channel", help="Preselect the channel")
    parser.add_argument("--slug", help="Preseed the slug")
    parser.add_argument("--title", help="Preseed the working title")
    parser.add_argument(
        "--from-json",
        type=Path,
        default=None,
        help="Non-interactive: read a filled intake dict from <path> and skip prompts",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)

    if args.from_json is not None:
        data = load_intake_json(args.from_json)
    else:
        if not sys.stdin.isatty():
            print(
                "intake.py: stdin is not a TTY and --from-json was not "
                "provided. For non-interactive use, pass --from-json <path> with a "
                "pre-filled intake dict (see `intake` subagent).",
                file=sys.stderr,
            )
            return 2
        try:
            data = collect_intake(args)
        except EOFError:
            print(
                "intake.py: stdin closed before intake finished. "
                "For non-interactive use, pass --from-json <path>.",
                file=sys.stderr,
            )
            return 2
        except KeyboardInterrupt:
            print("\nAborted by user.", file=sys.stderr)
            return 130

    print(build_summary(data))
    if args.from_json is None and not confirm(
        "\nCreate project scaffold from this brief?"
    ):
        print("Aborted.")
        return 1
    return run_scaffold(data)


if __name__ == "__main__":
    raise SystemExit(main())
