#!/usr/bin/env python3
"""CLI-first template catalog.

The source tree is the truth. `registry.json` is a generated/cache artifact for
the browser and validators, not the interface humans should hand-edit.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parent
REPO_ROOT = ROOT.parent
REGISTRY_PATH = ROOT / "registry.json"
REPO_ROOT_HINT = f"repo root: {REPO_ROOT}"
GENERATED_NOTE = "Generated by `pnpm template -- registry --write`; do not edit registry.json by hand."

CATEGORIES: dict[str, tuple[str, str]] = {
    "abstract": ("Atmospheric backgrounds: grain, dots, ink, waves", "abs"),
    "annotation": ("Marks and layers: notes, pins, highlights, flips", "annot"),
    "callout": ("On-screen annotations: arrows, circles, magnify crops", "callout"),
    "cinematic": ("Film grain, letterbox, parallax, vignette", "cine"),
    "collage": ("Retro collage, aged paper, halftone, bold type", "collage"),
    "comparison": ("A/B comparisons, splits, scales, spectrums", "comp"),
    "counter": ("Animated numbers, odometers, tickers, split-flaps", "counter"),
    "data-viz": ("Spring-physics data visualization", "dataviz"),
    "diagram": ("Process flows, org charts, funnels", "diagram"),
    "editorial": ("Print journalism: front pages, banners, dossiers", "edit"),
    "geo": ("Animated maps, route traces, choropleths", "geo"),
    "hero": ("Opening title cards, stat heroes, section headers", "hero"),
    "image-comp": ("Framed images, cutouts, editorial grids", "imgcomp"),
    "indian": ("Indian design: Mughal, temple, textile, Rajasthani", "indian"),
    "kinetic-text": ("Word animations and subtitle burns", "ktext"),
    "lower-thirds": ("Speaker labels, source citations, fact boxes", "lt"),
    "meter": ("Gauges, meters, rings, progress states", "meter"),
    "narrative": ("Text-driven narrative moments", "narr"),
    "reveal": ("Dramatic disclosures and reveals", "reveal"),
    "screen": ("Browser, phone, terminal, document metaphors", "screen"),
    "social-proof": ("Logo walls, leaderboards, flag grids", "social"),
    "swarajya-kit": ("Swarajya editorial YouTube kit", "sk"),
    "timeline": ("Historical event timelines", "tl"),
    "transitions": ("Structural punctuation: punches, wipes, dissolves", "trans"),
}

SKIP_FILES = {"demo.tsx", "index.ts", "index.tsx", "Root.tsx", "root.tsx", "_test-geo.ts", "_extract-paths.ts"}
COMPONENT_RE = re.compile(r"export\s+const\s+([A-Z][A-Za-z0-9_]*)\b")
DEMO_RE = re.compile(r"export\s+const\s+demo\s*=\s*\{(?P<body>.*?)\n\}", re.DOTALL)
DEMO_PROPS_RE = re.compile(r"props\s*:\s*\{(?P<body>.*?)\n\s*\}\s*(?:satisfies\s+\w+)?\s*,?", re.DOTALL)
PROPS_INTERFACE_RE = re.compile(
    r"(?:export\s+)?interface\s+(?P<name>[A-Za-z0-9_]*Props)\s*(?:extends\s+[A-Za-z0-9_, <>{}]+)?\s*\{(?P<body>.*?)\n\}",
    re.DOTALL,
)
PROP_LINE_RE = re.compile(r"^\s*(?P<name>[A-Za-z0-9_]+)(?P<optional>\?)?\s*:\s*(?P<type>[^;]+);?")
STRING_FIELD_RE = re.compile(r'(?P<key>[A-Za-z0-9_]+)\s*:\s*"(?P<value>[^"]*)"')
NUMBER_FIELD_RE = re.compile(r"(?P<key>[A-Za-z0-9_]+)\s*:\s*(?P<value>\d+)")

SUGGEST_KEYWORDS: dict[str, tuple[str, ...]] = {
    "map": ("geo/", "map", "country", "city", "route", "territory", "choropleth", "india"),
    "city": ("city", "marker", "map", "pin", "location"),
    "cities": ("city", "marker", "map", "pin", "location"),
    "route": ("route", "trace", "path", "journey", "movement"),
    "migration": ("route", "trace", "journey", "flow", "movement"),
    "highlight": ("highlight", "callout", "marker", "pin", "country", "region"),
    "india": ("india", "city", "map", "state", "country"),
    "compare": ("compare", "comparison", "multi", "split", "versus"),
    "population": ("choropleth", "data", "map", "comparison", "city"),
}


@dataclass
class Template:
    id: str
    category: str
    file: str
    composition_id: str
    export_name: str
    duration_frames: int = 180
    status: str = "draft"
    version: int = 1
    created_at: str | None = None
    qc: Any = None
    notes: list[str] = field(default_factory=list)
    has_demo: bool = False

    def as_registry_entry(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "category": self.category,
            "file": self.file,
            "compositionId": self.composition_id,
            "exportName": self.export_name,
            "status": self.status,
            "version": self.version,
            "durationFrames": self.duration_frames,
            "createdAt": self.created_at or datetime.now().isoformat(),
            "qc": self.qc,
        }

    @property
    def path(self) -> Path:
        return ROOT / self.file


def load_registry() -> dict[str, Any]:
    if not REGISTRY_PATH.exists():
        return {"version": "1.0.0", "categories": {}, "templates": {}, "backlog": []}
    return json.loads(REGISTRY_PATH.read_text(encoding="utf-8"))


def demo_fields(text: str) -> dict[str, Any]:
    match = DEMO_RE.search(text)
    if not match:
        return {}
    body = match.group("body")
    fields: dict[str, Any] = {m.group("key"): m.group("value") for m in STRING_FIELD_RE.finditer(body)}
    fields.update({m.group("key"): int(m.group("value")) for m in NUMBER_FIELD_RE.finditer(body)})
    return fields


def demo_props_text(text: str) -> str | None:
    demo = DEMO_RE.search(text)
    if not demo:
        return None
    props = DEMO_PROPS_RE.search(demo.group("body"))
    if not props:
        return None
    return "{\n" + props.group("body").rstrip() + "\n}"


def source_for(template: Template) -> str:
    return template.path.read_text(encoding="utf-8")


def props_info(template: Template) -> dict[str, Any]:
    source = source_for(template)
    interfaces = []
    for match in PROPS_INTERFACE_RE.finditer(source):
        body = match.group("body")
        props = []
        for line in body.splitlines():
            line = line.strip()
            prop_match = PROP_LINE_RE.match(line)
            if not prop_match:
                continue
            props.append(
                {
                    "name": prop_match.group("name"),
                    "required": not bool(prop_match.group("optional")),
                    "type": prop_match.group("type").strip(),
                }
            )
        interfaces.append({"name": match.group("name"), "props": props, "raw": body.strip()})

    required = []
    optional = []
    if interfaces:
        for prop in interfaces[0]["props"]:
            (required if prop["required"] else optional).append({"name": prop["name"], "type": prop["type"]})

    return {
        "id": template.id,
        "file": template.file,
        "path": str((ROOT / template.file).resolve()),
        "repoRoot": str(REPO_ROOT),
        "interface": interfaces[0]["name"] if interfaces else None,
        "required": required,
        "optional": optional,
        "demoProps": demo_props_text(source),
        "notes": template.notes,
    }


def scan() -> list[Template]:
    registry_templates = load_registry().get("templates", {})
    templates: list[Template] = []

    for category, (_description, prefix) in CATEGORIES.items():
        category_dir = ROOT / category
        if not category_dir.is_dir():
            continue
        for path in sorted(category_dir.glob("*.tsx")):
            if path.name in SKIP_FILES or path.name.startswith("_"):
                continue
            source = path.read_text(encoding="utf-8")
            component_match = COMPONENT_RE.search(source)
            if not component_match:
                continue

            stem = path.stem
            template_id = f"{category}/{stem}"
            fields = demo_fields(source)
            existing = registry_templates.get(template_id, {})
            composition_id = str(fields.get("compositionId") or existing.get("compositionId") or f"{prefix}-{stem}")
            duration_frames = int(fields.get("durationInFrames") or existing.get("durationFrames") or 180)

            template = Template(
                id=template_id,
                category=category,
                file=f"{category}/{path.name}",
                composition_id=composition_id,
                export_name=component_match.group(1),
                duration_frames=duration_frames,
                status=str(existing.get("status") or "draft"),
                version=int(existing.get("version") or 1),
                created_at=existing.get("createdAt") if isinstance(existing.get("createdAt"), str) else None,
                qc=existing.get("qc"),
                has_demo=bool(fields),
            )
            if not fields:
                template.notes.append("missing demo export")
            if not props_info(template)["interface"]:
                template.notes.append("missing props interface")
            templates.append(template)

    return templates


def categories_payload() -> dict[str, dict[str, Any]]:
    return {
        name: {
            "description": description,
            "directory": name,
            "compositionPrefix": prefix,
            "status": "active",
        }
        for name, (description, prefix) in CATEGORIES.items()
    }


def command_list(args: argparse.Namespace) -> int:
    templates = scan()
    if args.category:
        templates = [t for t in templates if t.category == args.category]
    if args.status:
        templates = [t for t in templates if t.status == args.status]
    if args.json:
        print(json.dumps([t.as_registry_entry() for t in templates], indent=2))
        return 0
    for t in templates:
        print(f"{t.id:<38} {t.status:<13} {t.composition_id:<32} {t.export_name}")
    print(f"\n{len(templates)} templates")
    print(REPO_ROOT_HINT)
    return 0


def command_find(args: argparse.Namespace) -> int:
    query = " ".join(args.query).lower()
    words = [part for part in re.split(r"[^a-z0-9]+", query) if part]
    matches: list[Template] = []
    for t in scan():
        haystack = searchable_text(t)
        if all(word in haystack for word in words):
            matches.append(t)
    for t in matches:
        print(f"{t.id:<38} {t.status:<13} {REPO_ROOT / 'templates' / t.file}")
    print(f"\n{len(matches)} matches")
    print(REPO_ROOT_HINT)
    return 0 if matches else 1


def searchable_text(template: Template) -> str:
    category_desc = CATEGORIES.get(template.category, ("", ""))[0]
    try:
        source = source_for(template)
    except OSError:
        source = ""
    return f"{template.id} {template.category} {category_desc} {template.file} {template.composition_id} {template.export_name} {source[:4000]}".lower()


def command_show(args: argparse.Namespace) -> int:
    template = next((t for t in scan() if t.id == args.template_id), None)
    if template is None:
        print(f"template not found: {args.template_id}", file=sys.stderr)
        return 1
    payload = template.as_registry_entry()
    payload["path"] = str((ROOT / template.file).resolve())
    payload["repoRoot"] = str(REPO_ROOT)
    payload["notes"] = template.notes
    payload["propsSummary"] = {
        "required": [item["name"] for item in props_info(template)["required"]],
        "optional": [item["name"] for item in props_info(template)["optional"]],
    }
    print(json.dumps(payload, indent=2))
    return 0


def command_props(args: argparse.Namespace) -> int:
    template = next((t for t in scan() if t.id == args.template_id), None)
    if template is None:
        print(f"template not found: {args.template_id}", file=sys.stderr)
        return 1
    info = props_info(template)
    if args.json:
        print(json.dumps(info, indent=2))
        return 0
    print(f"{info['id']}")
    print(f"repo root: {info['repoRoot']}")
    print(f"file: {info['path']}")
    print(f"interface: {info['interface'] or 'not found'}")
    if info["required"]:
        print("\nrequired:")
        for item in info["required"]:
            print(f"- {item['name']}: {item['type']}")
    if info["optional"]:
        print("\noptional:")
        for item in info["optional"]:
            print(f"- {item['name']}: {item['type']}")
    if info["demoProps"]:
        print("\ndemo props:")
        print(info["demoProps"])
    if info["notes"]:
        print("\nnotes:")
        for note in info["notes"]:
            print(f"- {note}")
    return 0 if info["interface"] else 1


def score_template(template: Template, words: list[str]) -> int:
    haystack = searchable_text(template)
    score = 0
    for word in words:
        expanded = SUGGEST_KEYWORDS.get(word, (word,))
        for term in expanded:
            if term in haystack:
                score += 3 if term in template.id.lower() else 1
    if template.category == "geo":
        score += 2
    if template.id in {"swarajya-kit/map-callout", "swarajya-kit/map-dots", "hero/map-title"}:
        score += 2
    if template.status in {"approved", "in-review"}:
        score += 1
    return score


def command_suggest(args: argparse.Namespace) -> int:
    query = " ".join(args.intent).lower()
    words = [part for part in re.split(r"[^a-z0-9]+", query) if part]
    ranked = sorted(
        ((score_template(t, words), t) for t in scan()),
        key=lambda item: (-item[0], item[1].id),
    )
    matches = [(score, template) for score, template in ranked if score > 0][: args.limit]
    for score, template in matches:
        reason_bits = []
        if template.category == "geo":
            reason_bits.append("geo map family")
        if "city" in query and ("city" in template.id or "marker" in template.id):
            reason_bits.append("city/marker fit")
        if "route" in query or "migration" in query:
            if "route" in template.id or "trace" in template.id:
                reason_bits.append("movement/path fit")
        if "highlight" in query and any(term in template.id for term in ("highlight", "callout", "marker", "map")):
            reason_bits.append("highlight/callout fit")
        reason = ", ".join(reason_bits) if reason_bits else "keyword match"
        print(f"{template.id:<38} score={score:<2} {template.status:<13} {reason}")
        print(f"  file: {REPO_ROOT / 'templates' / template.file}")
    print(f"\n{len(matches)} suggestions")
    print(REPO_ROOT_HINT)
    return 0 if matches else 1


def command_smoke(args: argparse.Namespace) -> int:
    template = next((t for t in scan() if t.id == args.template_id), None)
    if template is None:
        print(f"template not found: {args.template_id}", file=sys.stderr)
        return 1
    info = props_info(template)
    problems = []
    if not template.path.exists():
        problems.append("source file missing")
    if args.example == "default" and not info["demoProps"]:
        problems.append("default demo/example props missing")
    if not info["interface"]:
        problems.append("props interface missing")

    tsc = subprocess.run(
        ["npx", "--prefix", str(ROOT), "tsc", "--noEmit"],
        cwd=ROOT.parent,
        capture_output=True,
        text=True,
        check=False,
    )
    if tsc.returncode != 0:
        first_line = (tsc.stdout + tsc.stderr).strip().splitlines()
        problems.append(f"typescript failed: {first_line[0] if first_line else 'unknown error'}")

    if problems:
        print(f"smoke failed: {template.id}")
        for problem in problems:
            print(f"- {problem}")
        return 1
    print(f"smoke ok: {template.id} ({args.example})")
    print(REPO_ROOT_HINT)
    return 0


def command_registry(args: argparse.Namespace) -> int:
    old = load_registry()
    templates = scan()
    payload = {
        "_generated": {
            "note": GENERATED_NOTE,
            "command": "pnpm template -- registry --write",
            "repoRoot": str(REPO_ROOT),
            "sourceRoot": str(ROOT),
        },
        "version": old.get("version", "1.0.0"),
        "updated": datetime.now().strftime("%Y-%m-%d"),
        "categories": categories_payload(),
        "templates": {t.id: t.as_registry_entry() for t in templates},
        "backlog": old.get("backlog", []),
    }
    text = json.dumps(payload, indent=2, ensure_ascii=False) + "\n"
    if args.write:
        REGISTRY_PATH.write_text(text, encoding="utf-8")
        print(f"wrote {REGISTRY_PATH} with {len(templates)} templates")
        print(REPO_ROOT_HINT)
    else:
        print(text, end="")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="template", description="CLI-first Varnam template catalog")
    sub = parser.add_subparsers(dest="command", required=True)

    list_parser = sub.add_parser("list", help="list templates")
    list_parser.add_argument("--category")
    list_parser.add_argument("--status")
    list_parser.add_argument("--json", action="store_true")
    list_parser.set_defaults(func=command_list)

    find_parser = sub.add_parser("find", help="search templates")
    find_parser.add_argument("query", nargs="+")
    find_parser.set_defaults(func=command_find)

    show_parser = sub.add_parser("show", help="show one template")
    show_parser.add_argument("template_id")
    show_parser.set_defaults(func=command_show)

    props_parser = sub.add_parser("props", help="show best-effort props info")
    props_parser.add_argument("template_id")
    props_parser.add_argument("--json", action="store_true")
    props_parser.set_defaults(func=command_props)

    suggest_parser = sub.add_parser("suggest", help="rank templates for an intent")
    suggest_parser.add_argument("intent", nargs="+")
    suggest_parser.add_argument("--limit", type=int, default=8)
    suggest_parser.set_defaults(func=command_suggest)

    smoke_parser = sub.add_parser("smoke", help="smoke-check one template example")
    smoke_parser.add_argument("template_id")
    smoke_parser.add_argument("--example", default="default")
    smoke_parser.set_defaults(func=command_smoke)

    registry_parser = sub.add_parser("registry", help="emit generated registry.json")
    registry_parser.add_argument("--write", action="store_true")
    registry_parser.set_defaults(func=command_registry)

    return parser


def main(argv: list[str] | None = None) -> int:
    if argv is None:
        argv = sys.argv[1:]
    if argv[:1] == ["--"]:
        argv = argv[1:]
    args = build_parser().parse_args(argv)
    return int(args.func(args))


if __name__ == "__main__":
    raise SystemExit(main())
