import {
  displaySansFamily,
  sansFamily,
  serifFamily,
} from "./fonts";
import type { IdentityPack } from "./types";

export const defaultIdentityPack: IdentityPack = {
  id: "default",
  colors: {
    canvas: "#EDEAE4",
    canvasStrong: "#0A0A0A",
    surface: "#C8C2B6",
    surfaceMuted: "#F4F0EA",
    textPrimary: "#2A2622",
    textSecondary: "#5C5650",
    textMuted: "#9B948B",
    textInverse: "#EDEAE4",
    lineSubtle: "#C8C2B6",
    accentPrimary: "#C17A48",
    accentSecondary: "#907070",
    accentPositive: "#6D917D",
    accentNegative: "#907070",
    neutral: "#7A8999",
  },
  typography: {
    display: {
      family: serifFamily,
      size: 80,
      weight: 400,
      lineHeight: 1.06,
      letterSpacingEm: -0.02,
    },
    title: {
      family: serifFamily,
      size: 72,
      weight: 400,
      lineHeight: 1.1,
      letterSpacingEm: -0.02,
    },
    subtitle: {
      family: sansFamily,
      size: 32,
      weight: 500,
      lineHeight: 1.45,
    },
    body: {
      family: sansFamily,
      size: 28,
      weight: 400,
      lineHeight: 1.55,
    },
    label: {
      family: sansFamily,
      size: 20,
      weight: 700,
      lineHeight: 1.2,
      letterSpacingEm: 0.18,
      textTransform: "uppercase",
    },
    meta: {
      family: sansFamily,
      size: 20,
      weight: 500,
      lineHeight: 1.3,
      letterSpacingEm: 0.08,
      textTransform: "uppercase",
    },
    number: {
      family: serifFamily,
      size: 200,
      weight: 400,
      lineHeight: 0.9,
      letterSpacingEm: -0.03,
    },
  },
  spacing: {
    pageInsetX: 120,
    pageInsetY: 48,
    sectionGap: 56,
    contentGap: 24,
    tightGap: 12,
    panelGap: 56,
    safeZone: 80,
    radiusSm: 4,
    radiusMd: 8,
    radiusLg: 16,
    borderThin: 1,
    borderThick: 3,
  },
  motion: {
    revealDuration: 18,
    lineGrowDuration: 25,
    kenBurnsFrom: 1.03,
    kenBurnsTo: 1.08,
    emphasisScale: 1.06,
  },
  ornament: {
    shadowSoft: "0 8px 40px rgba(0,0,0,0.08)",
    shadowStrong: "0 12px 56px rgba(0,0,0,0.2)",
    dividerRadius: 2,
    badgeBackground: "#907070",
    badgeForeground: "#2A2622",
    overlayGradientStart: "rgba(10,10,10,0.88)",
    overlayGradientMid: "rgba(10,10,10,0.6)",
    overlayGradientEnd: "transparent",
  },
};

export const tacticalDisplayFamily = displaySansFamily;
