name: Extract ZIP

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Show Files
        run: ls -la

      - name: Extract ZIP
        run: |
          mkdir -p extracted
          unzip "AI video Generator.zip" -d extracted

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add .

          git commit -m "Extract ZIP content" || echo "No changes to commit"

          git push
